<a href="https://colab.research.google.com/github/satyhim/Machine_Learning/blob/main/Homework_Ensemble_Technique2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import tree
import matplotlib.pyplot as plt
%matplotlib inline

In [94]:
df= pd.read_excel('/content/drive/MyDrive/Python/Project/seeds_dataset.xlsx')

In [95]:
df.head()

Area  Perimeter  Compactness  Length of Kernel  Width of Kernel  \
0  15.26      14.84       0.8710             5.763            3.312   
1  14.88      14.57       0.8811             5.554            3.333   
2  14.29      14.09       0.9050             5.291            3.337   
3  13.84      13.94       0.8955             5.324            3.379   
4  16.14      14.99       0.9034             5.658            3.562   

   Asymmetry coefficient  Length of kernel groove  Class (1_2_3  
0                  2.221                    5.220             1  
1                  1.018                    4.956             1  
2                  2.699                    4.825             1  
3                  2.259                    4.805             1  
4                  1.355                    5.175             1

In [96]:
# importing libraries
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [97]:
X = df.drop(['Class (1_2_3'], axis=1)

y = df['Class (1_2_3']

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 100)
	

In [99]:
clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

In [100]:
clf_gini.fit(X_train, y_train)
clf_gini

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)

In [101]:
y_pred = clf_gini.predict(X_test)
y_pred

array([1, 3, 1, 3, 2, 1, 3, 2, 3, 3, 2, 2, 2, 1, 2, 1, 1, 2, 1, 3, 2, 2,
       2, 2, 3, 1, 2, 1, 1, 1, 3, 1, 3, 3, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2,
       1, 3, 3, 1, 3, 2, 1, 3, 3, 3, 1, 3, 3, 1, 1, 2, 1, 2, 2])

In [102]:
print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)

Accuracy :  90.47619047619048


#Simple Ensemble Techniques

In this section, we will look at a few simple but powerful techniques, namely:

1 Max Voting

2 Averaging

3 Weighted Averaging

**1 Max Voting**

In [103]:
from sklearn.ensemble import VotingClassifier
model1 = LogisticRegression(random_state=1)
model2 = tree.DecisionTreeClassifier(random_state=1)
model = VotingClassifier(estimators=[('lr',model1), ('dt', model2)], voting='hard')
model.fit(X_train,y_train)
Md = model.score(X_test,y_test)
print('Model_Score is :',Md)

Model_Score is : 0.9523809523809523


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


#Averaging

In [104]:
from sklearn.neighbors import KNeighborsClassifier
model1 = tree.DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()

model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

pred1 = model1.predict_proba(X_test)
pred2 = model2.predict_proba(X_test)
pred3 = model3.predict_proba(X_test)

finalpred = (pred1 + pred2 + pred3)/3
print('The Finalpred is :\n',finalpred)

The Finalpred is :
 [[6.73409320e-01 2.92955431e-04 3.26297725e-01]
 [1.03733763e-02 9.76937543e-06 9.89616854e-01]
 [4.45833160e-01 1.13847939e-04 5.54052992e-01]
 [2.53328655e-01 2.56441187e-04 7.46414904e-01]
 [1.61334886e-02 9.83866434e-01 7.72541855e-08]
 [8.60419057e-01 3.64292123e-04 1.39216651e-01]
 [3.25647229e-04 1.05131984e-06 9.99673301e-01]
 [9.37564809e-05 9.99906243e-01 3.39251438e-10]
 [1.47625888e-03 8.13749132e-07 9.98522927e-01]
 [3.33237394e-03 1.35299956e-05 9.96654096e-01]
 [8.27645574e-04 9.99172354e-01 4.73883791e-10]
 [1.75343242e-03 9.98246260e-01 3.07142329e-07]
 [4.96032520e-03 9.95039658e-01 1.68140539e-08]
 [9.82881138e-01 3.33651092e-03 1.37823510e-02]
 [3.16616810e-02 9.68117690e-01 2.20628648e-04]
 [8.00576074e-01 1.98613403e-01 8.10522501e-04]
 [2.21530773e-01 6.30009992e-04 7.77839217e-01]
 [2.92735895e-02 9.70713282e-01 1.31287724e-05]
 [8.53935786e-01 5.93496295e-04 1.45470718e-01]
 [1.23960432e-02 5.84287615e-05 9.87545528e-01]
 [1.48450492e-01 8.5

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [105]:
models = [('Decision Tree', DecisionTreeClassifier()),
         ('KNN', KNeighborsClassifier()),
         ('Naive Bayes', GaussianNB())]
for name, model in models:
    model.fit(X_train, y_train)
    
    prediction = model.predict(X_test)
    score = accuracy_score(y_test, prediction)
    print('{} Model Accuracy: {}'.format(name,score))

Decision Tree Model Accuracy: 0.9682539682539683
KNN Model Accuracy: 0.9682539682539683
Naive Bayes Model Accuracy: 0.9841269841269841


#3 Weighted Average

In [106]:
model1 = tree.DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()

model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

pred1 = model1.predict_proba(X_test)
pred2 = model2.predict_proba(X_test)
prad3 = model3.predict_proba(X_test)

finalpred = (pred1*0.3 + pred2*0.3 + pred3*0.4)
print('The Finalpred is:\n',finalpred)

The Finalpred is:
 [[3.68091184e-01 3.51546517e-04 6.31557270e-01]
 [1.24480516e-02 1.17232505e-05 9.87540225e-01]
 [7.94999792e-01 1.36617526e-04 2.04863591e-01]
 [2.63994385e-01 3.07729425e-04 7.35697885e-01]
 [1.93601863e-02 9.80639721e-01 9.27050226e-08]
 [8.72502869e-01 4.37150547e-04 1.27059981e-01]
 [3.90776674e-04 1.26158380e-06 9.99607962e-01]
 [1.12507777e-04 9.99887492e-01 4.07101726e-10]
 [1.77151066e-03 9.76498958e-07 9.98227513e-01]
 [3.99884872e-03 1.62359947e-05 9.95984915e-01]
 [9.93174689e-04 9.99006825e-01 5.68660549e-10]
 [2.10411890e-03 9.97895513e-01 3.68570795e-07]
 [5.95239023e-03 9.94047590e-01 2.01768646e-08]
 [9.79457366e-01 4.00381310e-03 1.65388212e-02]
 [3.79940172e-02 9.61741228e-01 2.64754377e-04]
 [8.00691289e-01 1.98336084e-01 9.72627001e-04]
 [2.25836928e-01 7.56011991e-04 7.73407060e-01]
 [3.51283074e-02 9.64855938e-01 1.57545269e-05]
 [8.64722943e-01 7.12195554e-04 1.34564861e-01]
 [1.48752519e-02 7.01145138e-05 9.85054634e-01]
 [1.58140590e-01 8.40

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [107]:
# evaluate a weighted average ensemble for classification
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
 


In [108]:
# get a list of base models
def get_models():
	models = list()
	models.append(('lr', LogisticRegression()))
	models.append(('cart', DecisionTreeClassifier()))
	models.append(('bayes', GaussianNB()))
	return models
 
# evaluate each base model
def evaluate_models(models, X_train, X_test, y_train, y_test):
	# fit and evaluate the models
	scores = list()
	for name, model in models:
		# fit the model
		model.fit(X_train, y_train)
		# evaluate the model
		y_pred = model.predict(X_test)
		acc = accuracy_score(y_test, y_pred)
		# store the performance
		scores.append(acc)
		# report model performance
	return scores

# create the base models
models = get_models()
 
# fit and evaluate each model
scores = evaluate_models(models, X_train, X_test, y_train, y_test)
print(scores)
# create the ensemble
ensemble = VotingClassifier(estimators=models, voting='soft', weights=scores)
# fit the ensemble on the training dataset
ensemble.fit(X_train, y_train)
# make predictions on test set
y_pred = ensemble.predict(X_test)
# evaluate predictions
score = accuracy_score(y_test, y_pred)
print('Weighted Avg Accuracy: %.3f' % (score))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[0.9841269841269841, 0.9206349206349206, 0.9841269841269841]
Weighted Avg Accuracy: 1.000


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
